### ISSUE TITLE
One question about the simulator of `DPDP Competition`.

### ISSUE THREAD

**Issue by Dongbox** [huawei-noah/xingtian#13]
## What's the function of file `output_route.json`? 

I mean it looks like the file `output_destination.json` could support it finishes all the plans since it contains the information of order involving the items, factories about pickup and delivery, and of course the vehicle itself.

Or it will auto-updated that the destination of the vehicle by the planned route when it reached the destination and after pickup?

**Comment by zgfhill** [comment]
Yes, when a vehicle reaches its destination, the simulator will generate a new destination from the planned_route. The planned_route in a vehicle object comes from output_route.json file which is calculated by the algorithm.
