### ISSUE TITLE
关于模拟器的几个问题

### ISSUE THREAD

**Issue by ChasionNo1** [huawei-noah/xingtian#15]
你好，有几个问题希望可以得到解答。
1、xingtian可以在window下运行吗？
2、“A Hierarchical Reinforcement Learning Based Optimization Framework for Large-scale Dynamic Pickup and Delivery Problems”这篇论文提到dpdp模拟器，文中的分层智能体算法在哪里可以找到？

**Comment by hustqj** [comment]
我们没有在window上测试过刑天，以前有人尝试，应该需要做少量的改动

**Comment by hustqj** [comment]
论文中提到的算法目前尚未开源

**Comment by Phil610351** [comment]
A Hierarchical Reinforcement Learning Based Optimization Framework for Large-scale Dynamic Pickup and Delivery Problems 什么时候开源呢？？？

**Comment by Phil610351** [comment]
A Hierarchical Reinforcement Learning Based Optimization Framework for Large-scale Dynamic Pickup and Delivery Problems 什么时候开源呢？？？

**Comment by Phil610351** [comment]
A Hierarchical Reinforcement Learning Based Optimization Framework for Large-scale Dynamic Pickup and Delivery Problems 什么时候开源呢？？？

**Comment by HQ-LV** [comment]
> 你好，有几个问题希望可以得到解答。 1、xingtian可以在window下运行吗？ 2、“A Hierarchical Reinforcement Learning Based Optimization Framework for Large-scale Dynamic Pickup and Delivery Problems”这篇论文提到dpdp模拟器，文中的分层智能体算法在哪里可以找到？

哈喽，请问你在Windows下测试刑天成功了吗？

**Comment by Phil610351** [comment]
A Hierarchical Reinforcement Learning Based Optimization Framework for Large-scale Dynamic Pickup and Delivery Problems 这篇论文的源代码，作者没开源。

**Comment by yyds-xtt** [comment]
什么玩意



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月21日(周一) 中午11:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huawei-noah/xingtian] 关于模拟器的几个问题 (Issue #15)




 
Closed #15.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChasionNo1** [comment]
这个是工程代码，没有参考价值，看起来费劲，到处都是封装，建议放弃！
