### ISSUE TITLE
关于使用yaml自定义模型

### ISSUE THREAD

**Issue by hecong97** [huawei-noah/xingtian#2]
1、关于使用yaml文件参数自定义模型，如果可以自定义卷积层或者全连接的层数易用性应该会更好一些？
2、好像没有实现lstm模块

**Comment by hustqj** [comment]
现在的确没有通过参数定义卷积或全连接层数，目前比较推荐用户自己定义模型文件，然后在yaml文件里面引用即可，lstm模块也可用户自己定义
