### ISSUE TITLE
增大explores数量，吞吐量没有相应增大

### ISSUE THREAD

**Issue by hzy111111** [huawei-noah/xingtian#30]
您好：
我复现了刑天的dqn算法，测试应用场景有Qbert、CartPole、LunarLander，使用的默认配置yaml文件运行，仅仅修改env_num（在单个节点下并行多实例explorer的数量）。发现随着explorers增大，吞吐量并没有随之增大。猜测可能是通信效率的问题，explorer采样一步后传递数据，多个explorer争夺锁导致吞吐量没有像预期地增大。

遇到的问题：单节点下增加explorer数量，吞吐量没有上升。

实验数据：1个explorer，吞吐量259；2个explorers，吞吐量355；4个explorers，吞吐量300；8个explorers，吞吐量311。

请问，我应该怎么设置才能得到近线性或较好的吞吐量加速比？期待您的回复，谢谢！

**Comment by hustqj** [comment]
DQN主要瓶颈是在learner训练那端，以atari为例leanrer收到4个step数据就会去replaybuffer里面取数据进行训练，所以你如果想取得比较高吞吐加速比，可以考虑在某些比较慢的env上做实验或者调整上面提到的4个step的参数

**Comment by hzy111111** [comment]
> DQN主要瓶颈是在learner训练那端，以atari为例leanrer收到4个step数据就会去replaybuffer里面取数据进行训练，所以你如果想取得比较高吞吐加速比，可以考虑在某些比较慢的env上做实验或者调整上面提到的4个step的参数

已解决，谢谢
：）
