### ISSUE TITLE
Hello,what is the zeus?

### ISSUE THREAD

**Issue by nbuliyang** [huawei-noah/xingtian#9]
Hello,what is the zeus?

**Comment by tmhm** [comment]
Good spot!  Zeus is a unified training framework inside that supports training with different backends, such as  MindSpore, TensorFlow, and PyTorch, which on different devices, likes GPU and NPU etc.
Do you like it？

**Comment by guikarist** [comment]
However, I found that almost all the codes in `zeus` are not used in `xt`, except `zeus.common` and `zeus.visual`.
Is `zeus` a separate project that is just used for convenience?

**Comment by guikarist** [comment]
> However, I found that almost all the codes in `zeus` are not used in `xt`, except `zeus.common` and `zeus.visual`.
> Is `zeus` a separate project that is just used for convenience?

Ah, I found it referenced in [another repo](https://github.com/huawei-noah/vega).

**Comment by tmhm** [comment]
@guikarist Yep, `zeus` will be a separate project for training.

**Comment by guikarist** [comment]
Cool!
